### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by AhmedMohamed2014** [nuno/TiCollectionView#73]
The example doesn't work and crash with alloy example.
The real module name is 'de.marcelpociot.collectionview', so why you write 'ti.collectionview'

**Comment by nuno** [comment]
@hansemannn can you please explain to him?
we have to 
1 rename android too or 
2 Put Back on iOS 

Thanks

**Comment by hansemannn** [comment]
Mhh, I didn't touch the Android naming, damn. "ti.collectionview" is easier to use (e.g. for Alloy views like `<CollectionView module="ti.collectionview" />`, so we should just change the Android module ID and bump it as well?

**Comment by AhmedMohamed2014** [comment]
and please check the examples in the example/ and android/example/ folders, they are different and crashes with alloy

Thanks

**Comment by nuno** [comment]
@m1ga  do you want change the mod id to "ti.collectionview" in android and bump to version 2.0 ?

**Comment by m1ga** [comment]
sure: https://github.com/nuno/TiCollectionView/pull/76/

**Comment by nuno** [comment]
Many thanks to both  @hansemannn and @m1ga you guys rock!

**Comment by ottopic** [comment]
I'm trying android 2.0 version with your last example but it seems doesn't works.
Who can help me?

`
[ERROR] :  TiApplication: (main) [1,3112] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.collectiont/org.appcelerator.titanium.TiActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.marcelpociot.collectionview.CollectionViewTemplate$DataItem.setDefaultProperties(org.appcelerator.kroll.KrollDict)' on a null object reference; Titanium 6.2.2,2017/09/19 16:01,undefined

[ERROR] :  TiApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.admob/org.appcelerator.titanium.TiActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.marcelpociot.collectionview.CollectionViewTemplate$DataItem.setDefaultProperties(org.appcelerator.kroll.KrollDict)' on a null object reference
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] :  TiApplication: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.marcelpociot.collectionview.CollectionViewTemplate$DataItem.setDefaultProperties(org.appcelerator.kroll.KrollDict)' on a null object reference
[ERROR] :  TiApplication: 	at de.marcelpociot.collectionview.CollectionViewTemplate.bindProxiesAndProperties(CollectionViewTemplate.java:152)
[ERROR] :  TiApplication: 	at de.marcelpociot.collectionview.CollectionViewTemplate.processChildProperties(CollectionViewTemplate.java:172)
[ERROR] :  TiApplication: 	at de.marcelpociot.collectionview.CollectionViewTemplate.processProperties(CollectionViewTemplate.java:161)
[ERROR] :  TiApplication: 	at de.marcelpociot.collectionview.CollectionViewTemplate.<init>(CollectionViewTemplate.java:110)
[ERROR] :  TiApplication: 	at de.marcelpociot.collectionview.CollectionView.processTemplates(CollectionView.java:682)
[ERROR] :  TiApplication: 	at de.marcelpociot.collectionview.CollectionView.processProperties(CollectionView.java:435)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1222)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:516)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:507)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:485)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:523)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:507)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:485)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:695)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:588)
[ERROR] :  TiApplication: 	at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:261)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:564)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:684)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:21)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:6237)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
[ERROR] :  TiApplication: 	... 9 more`

**Comment by nuno** [comment]
@ottopic Thanks, seems the example was not updated to reflect the new mod. id name.
Check my last commit. 
Remember the name of the module changed, to "ti.collectionview", so if you see any error with name "de.marcelpociot.collectionview.CollectionView" try find and replace.

Some  widgets like:  nl.fokkezb.pullToRefresh  and nl.fokkezb.infiniteScroll may need add this "ti.collectionview" the array, like I did in the example -> https://github.com/nuno/TiCollectionView/commit/40623191431ed4d13c6b76aa0eff049e5e0bb114#diff-48e9c12d1852e32be67c8c6b697b42b3R18

**Comment by ottopic** [comment]
@nuno that's the problem. I have used your example https://github.com/nuno/TiCollectionView/blob/master/example/app.js that report correct name and android dist 2.0.0 (https://github.com/nuno/TiCollectionView/blob/master/dist/ti.collectionview-android-2.0.0.zip) . 

So, how I can solve it?

**Comment by nuno** [comment]
@ottopic  please make sure the name is correct on tiapp.xml  or you have to give me more info.

with the example fixed and with correct name on tiapp.xml should work. Please clear the project first before the next build ;)

**Comment by ottopic** [comment]
@nuno I can confirm the problem because I have created new project to test it. I add the module width Titanium interface than I use:

`var TiCollectionView = require('ti.collectionview');`
and
`var collectionView = TiCollectionView.createCollectionView(`

I can attach the project if necessary.

**Comment by nuno** [comment]
@ottopic I think I found the cause, on android the new module name is not 100& migrated yet.

Look at https://github.com/nuno/TiCollectionView/issues/79

Sorry about that.

**Comment by ottopic** [comment]
@nuno thank you. No problem for the bug, the goal is fix it. :) 
I think this module is very important!

**Comment by nuno** [comment]
attach the project please

**Comment by m1ga** [comment]
I was running the example without any errors so I'm not sure if changing the `getApiName()` method will change anything. I'll do the changes in #79 but I think the problem is somewhere else.

**Comment by AhmedMohamed2014** [comment]
@ottopic try it without nl.fokkezb.pullToRefresh

**Comment by m1ga** [comment]
right, I removed that widget too! Since it isn't part of the module (and if you use 6.2.2 you can use the build in Refresh SDK!)

**Comment by ottopic** [comment]
I confirm the problem. Project in attachment


[collectionview.zip](https://github.com/nuno/TiCollectionView/files/1369201/collectionview.zip)

**Comment by m1ga** [comment]
The Alloy version works fine. Looks like the vanilla versions makes problems

**Comment by nuno** [comment]
Thanks @m1ga 
I submitted the PR on both
also with my last commit I changed all the names to ```ti.collectionview```
https://github.com/Topener/nl.fokkezb.infiniteScroll/pull/64
https://github.com/Topener/nl.fokkezb.pullToRefresh/pull/74

**Comment by nuno** [comment]
@ottopic for now you must use Alloy see https://github.com/nuno/TiCollectionView/issues/79

**Comment by ottopic** [comment]
@nuno thank you but my app is already build in Vanilla mod and I can't change to Alloy. I'll wait the fix.

**Comment by ottopic** [comment]
Are there news about this fix? Does nobody can try to solve it?
